feat(*): implement python client for openGemini
openGemini/openGemini-client-python pull request #3
Opened 2023-07-22 15:57 UTC by bbddbb1

support DDL
support write/query
support line protocol
support CI
#1

2023-07-24 06:54 UTC, shilinlee requested changes

2023-07-24 06:54 UTC, shilinlee commented on .github/workflows/ci.yml
> +      - '.gitignore'
```suggestion
```

2023-07-24 06:54 UTC, shilinlee commented on .github/workflows/ci.yml
> +        python-version: [ "3.7", "3.8", "3.9", "3.10", "3.11" ]
Is it necessary to run all of these versions? Is it appropriate to run the minimum version?

2023-07-24 07:46 UTC, shilinlee requested changes

2023-07-24 07:46 UTC, shilinlee commented on point.py
> +        if isinstance(field, str) and isinstance(value, str):
field_value should support `string`, `integer`, `bool`, `float`.

2023-07-24 07:46 UTC, shilinlee commented on point.py
> +        if isinstance(field, (list, tuple)) and isinstance(value, (list, tuple)):
len(field) should equal len(value)

2023-07-24 07:46 UTC, shilinlee commented on point.py
> +        if precision is None or precision == 'n':
```suggestion
        if precision is None or precision == 'ns':
```

2023-07-24 07:46 UTC, shilinlee commented on point.py
> +        if precision == 'u':
```suggestion
        if precision == 's' or precision == 'us' or precision == 'µs':
```

2023-07-24 07:46 UTC, shilinlee commented on point.py
> +        timestamp = parse(timestamp)
specify which precision.

2023-07-24 07:46 UTC, shilinlee commented on client.py
> +            self, host, port, username="root", password="root", database=None,
```suggestion
            self, host, port, username="", password="", database=None,
```

2023-07-24 07:46 UTC, shilinlee commented on client.py
> +            method = "POST"
method = "GET"

2023-07-24 07:46 UTC, shilinlee commented on client.py
> +        header["Content-Type"] = "application/octet-stream"
use `self._write_header`

2023-07-28 03:07 UTC, shilinlee requested changes

2023-07-28 03:07 UTC, shilinlee commented on client.py
> +        Create a new user.
```suggestion
        Create a new user.
        Create an admin user when admin is True.
        Create a general user when admin is False.
```

2023-07-28 03:07 UTC, shilinlee commented on client.py
> +        self.query(f"CREATE DATABASE {dbname}")
```suggestion
        self.query(f"CREATE DATABASE {dbname}", method="POST")
```

2023-07-28 03:07 UTC, shilinlee commented on client.py
> +        self.query(f"DROP DATABASE {dbname}")
```suggestion
        self.query(f"DROP DATABASE {dbname}", method="POST")
```

2023-07-28 03:07 UTC, shilinlee commented on client.py
> +        self.query(query)
```suggestion
        self.query(query, method="POST")
```

2023-07-28 03:07 UTC, shilinlee commented on client.py
> +        )
```suggestion
method="POST")
        )
```

2023-07-28 03:07 UTC, shilinlee commented on client.py
> +        self.query(query)
```suggestion
        self.query(query, method="POST")
```

2023-07-28 03:07 UTC, shilinlee commented on client.py
> +        self.query(query)
```suggestion
        self.query(query, method="POST")
```

2023-07-28 03:07 UTC, shilinlee commented on client.py
Add your test cases.

2023-08-02 08:53 UTC, shilinlee requested changes

2023-08-02 08:53 UTC, shilinlee commented on client.py
> +        header["Content-Type"] = "application/octet-stream"
```suggestion
```

2023-08-03 02:06 UTC, shilinlee approved these changes

2023-08-03 02:18 UTC, xiangyu5632 approved these changes

2023-08-03 02:23 UTC, merged