docs: modify the style of readme doc
openGemini/openGemini-client-python pull request #55
Opened 2024-07-28 15:52 UTC by zhiheng123

2024-07-31 22:43 UTC, shoothzj requested changes
Need updates with latest style

2024-08-04 10:51 UTC, zhiheng123 commented on README_CN.md
> +![License](https://img.shields.io/badge/license-Apache2.0-green) ![Language](https://img.shields.io/badge/Language-Python-blue.svg) [![version](https://img.shields.io/github/v/tag/opengemini/opengemi
Language and others should use Chinese in the Chinese description

2024-08-04 10:53 UTC, zhiheng123 commented on README_CN.md
> +`opengemini-client-python` 是一个用 python 编写的 OpenGemini 客户端。
without period

2024-08-06 13:51 UTC, shoothzj approved these changes

2024-08-06 13:51 UTC, merged